apiVersion: apps/v1
kind: Deployment
metadata:
  name: administrator-deployment
  labels:
    app: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: admin
        ports:
        - containerPort: 80