apiVersion: apps/v1
kind: Deployment
metadata:
  name: Product-deployment
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: product
        ports:
        - containerPort: 80